In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('250google_vector.csv')
df.head()

0         1         2         3         4         5         6  \
0 -0.181641  0.165039 -0.166016  0.357422 -0.092285  0.201172 -0.054688   
1  0.067871 -0.041260  0.100098  0.058838  0.054443  0.017578  0.072266   
2  0.121094  0.281250  0.106445  0.025635 -0.112305  0.040527 -0.006622   
3  0.079590  0.018799  0.109375  0.018677 -0.114258  0.120117  0.172852   
4 -0.026855  0.081055 -0.171875  0.227539 -0.141602  0.040527  0.229492   

          7         8         9    ...           292       293       294  \
0 -0.261719 -0.172852 -0.080566    ...     -0.149414  0.398438  0.092773   
1 -0.091309  0.072266  0.122559    ...     -0.150391  0.175781  0.106445   
2 -0.172852 -0.363281  0.142578    ...     -0.064941  0.074707  0.118164   
3 -0.020630  0.306641  0.267578    ...     -0.166016 -0.080078  0.144531   
4 -0.227539 -0.332031  0.131836    ...     -0.174805 -0.055176  0.197266   

        295       296       297       298       299  class       word  
0  0.033936 -0.061523  0.159180  0.127930  0.002228      0       food  
1  0.157227 -0.113281  0.104492 -0.085449 -0.154297      1    service  
2  0.185547  0.248047 -0.273438  0.072754  0.013489      2   ambience  
3  0.398438  0.064453 -0.066406  0.073242 -0.188477      3      value  
4  0.199219 -0.361328  0.101074  0.142578  0.281250      0  foodstuff  

[5 rows x 302 columns]

In [3]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [4]:
X=df.iloc[:,0:300].values.tolist()
y=df.iloc[:,300].values.tolist()
# from numpy import array
# X=array(X)
# y=array(y)

In [5]:
clf = SVC(kernel='rbf',C=1,gamma=0.1)
scores = cross_val_score(clf,X,y,cv=10,scoring='accuracy')
scores.mean()

0.835

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report,confusion_matrix
model = SVC()
model.fit(X,y)
predictions = model.predict(X)
#GridSearchCV是建立一個dictionary來組合要測試的參數
param_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}

#GridSearchCV算是一個meta-estimator，參數中帶有estimator，像是SVC，重點是會創造一個新的estimator，但又表現的一模一樣。也就是estimator=SVC時，就是作為分類器
#Verbose可設定為任一整數，它只是代表數字越高，文字解釋越多
grid = GridSearchCV(SVC(),param_grid,verbose=3)


D:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [7]:
#利用剛剛設定的參數來找到最適合的模型
grid.fit(X,y)

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ....................... C=0.1, gamma=1, score=0.25, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ........ C=0.1, gamma=1, score=0.27941176470588236, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................... C=0.1, gamma=1, score=0.453125, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.9264705882352942, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.8235294117647058, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................... C=0.1, gamma=0.1, score=0.6875, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ...... C=0.

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:    1.5s finished
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [8]:
#顯示最佳參數組合
grid.best_params_

{'C': 1, 'gamma': 0.1}

In [9]:
grid.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
grid_predictions = grid.predict(X)

In [11]:
print(confusion_matrix(y,predictions))
print('\n')
print(classification_report(y,grid_predictions))

[[48  2  0  0]
 [ 1 49  0  0]
 [ 0  6 42  2]
 [ 0 21  0 29]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.96      0.98      0.97        50
           2       0.98      1.00      0.99        50
           3       1.00      0.96      0.98        50

   micro avg       0.98      0.98      0.98       200
   macro avg       0.99      0.98      0.98       200
weighted avg       0.99      0.98      0.98       200

